### ISSUE TITLE
Entering an Esperanto word brings up that words definition

### ISSUE THREAD

**Issue by danbarbarito** [MichaelVessia/Vortaro#1]
I don't know if this is intended or not. The user is prompted to enter an English word, but they can type either an English word or Esperanto word to get its definition.

----------

Example:

Please enter an English word.
**zumilo**

The English Word zumilo has 1 possible definitions:
zumilo  =>  buzzer

**Comment by MichaelVessia** [comment]
It's intentional, but not fully functional, so I did not make it clear that it's a feature yet.  

I will need to make sure I properly handle unicode user input, as well as the "x-system" for user inputs.

An example of the x-system:
The Esperanto word for She is "ŝi"
It is valid and recognized by many keyboard to enter "sxi", where "sx" represents "ŝ"

**Comment by MichaelVessia** [comment]
Made this more clear though esperanto entry is not fully feature complete.  Filed other issues for these features.
